### ISSUE TITLE
Config for CIFAR-100

### ISSUE THREAD

**Issue by 2018cx** [Hansong-Zhang/M3D#2]
Good work! I notice some configs were missing. Can you share the configs for CIFAR-100? Thank you.

**Comment by 2018cx** [comment]
Also, does CIFAR-100 needs a multi-processing version?

**Comment by Hansong-Zhang** [comment]
> Good work! I notice some configs were missing. Can you share the configs for CIFAR-100? Thank you.

Hi cui,
Thank you for your interest on our work!
The configs for CIFAR-100 is the same as the ones for CIFAR-10, you can directly modify the dataset name in yaml file to use it. Besides, the CIFAR-100 does NOT need the multi-processing version, because it is a low-resolution dataset, a single process will be enough to handle it.

Best regards,
Hansong.
